# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crewship < Formula
  desc "Self-hosted runtime for AI coding agents — daemon + CLI + web UI in one binary"
  homepage "https://crewship.ai"
  version "0.1.0-beta.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship_0.1.0-beta.4_darwin_amd64.tar.gz"
      sha256 "711b0397d38f384b491c5be76d38fd7e6d9aaa2e12e18ecb7233e28583ebc82c"

      def install
        bin.install "crewship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship_0.1.0-beta.4_darwin_arm64.tar.gz"
      sha256 "ef94c107f4606564242a69a226352a06acc5acd8b2642cc540e8a47421e60896"

      def install
        bin.install "crewship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship_0.1.0-beta.4_linux_amd64.tar.gz"
        sha256 "9cbc88a6b5b0e307fa5d6cf274553b86d90e0fa74fa2a99da79b4f4840c36946"

        def install
          bin.install "crewship"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship_0.1.0-beta.4_linux_arm64.tar.gz"
        sha256 "fdd7236785a6ef821969de321f39681fe4a7cb240b18c2604ef47eb9f9d6aba6"

        def install
          bin.install "crewship"
        end
      end
    end
  end

  conflicts_with "crewship-cli"

  test do
    system "#{bin}/crewship", "version"
  end
end
