# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrewshipCli < Formula
  desc "Crewship CLI — lightweight client for a remote crewshipd (no daemon, no UI bundle)"
  homepage "https://crewship.ai"
  version "0.1.0-beta.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship-cli_0.1.0-beta.4_darwin_amd64.tar.gz"
      sha256 "4d2c89400fe66e769817c4eac454ee02811e29861876c32389d43999f7144a6e"

      def install
        bin.install "crewship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship-cli_0.1.0-beta.4_darwin_arm64.tar.gz"
      sha256 "38f311e1736c75d73f05d6cf98d0b104b7be09d39a6570df1602ae83f2222918"

      def install
        bin.install "crewship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship-cli_0.1.0-beta.4_linux_amd64.tar.gz"
        sha256 "9117172facca5e6e41033e96115f7bd70ac2c2ce6864a0b88716b4fca5855258"

        def install
          bin.install "crewship"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/crewship-ai/crewship/releases/download/v0.1.0-beta.4/crewship-cli_0.1.0-beta.4_linux_arm64.tar.gz"
        sha256 "72a00fadabe2c38cc7b9b33f37b818a419f1442f201cb8d1119cbdcb6a94ccc5"

        def install
          bin.install "crewship"
        end
      end
    end
  end

  conflicts_with "crewship"

  test do
    system "#{bin}/crewship", "version"
  end
end
